export const NATIVE_RESOURCES: Readonly<Record<string, string>> = Object.freeze({
  account_page: 'https://www.kobo.com/account/settings',
  account_page_rakuten: 'https://my.rakuten.co.jp/',
  autocomplete: 'https://storeapi.kobo.com/v1/products/autocomplete',
  book: 'https://storeapi.kobo.com/v1/products/books/{ProductId}',
  book_detail_page: 'https://www.kobo.com/{region}/{language}/ebook/{slug}',
  book_detail_page_rakuten: 'http://books.rakuten.co.jp/rk/{crossrevisionid}',
  book_landing_page: 'https://www.kobo.com/ebooks',
  categories: 'https://storeapi.kobo.com/v1/categories',
  category: 'https://storeapi.kobo.com/v1/categories/{CategoryId}',
  category_products: 'https://storeapi.kobo.com/v1/categories/{CategoryId}/products',
  client_authd_referral: 'https://authorize.kobo.com/api/AuthenticatedReferral/client/v1/getLink',
  content_access_book: 'https://storeapi.kobo.com/v1/products/{ProductId}/access',
  dictionary_host: 'https://ereaderfiles.kobo.com',
  discovery_host: 'https://discovery.kobobooks.com',
  display_accessibility_enabled: 'False',
  display_parental_controls_enabled: 'False',
  dropbox_link_account_poll: 'https://authorize.kobo.com/{region}/{language}/LinkDropbox',
  eula_page: 'https://www.kobo.com/termsofuse?style=onestore',
  featured_list: 'https://storeapi.kobo.com/v1/products/featured/{FeaturedListId}',
  featured_lists: 'https://storeapi.kobo.com/v1/products/featured',
  feedback: '',
  free_books_page: 'https://www.kobo.com/{region}/{language}/p/free-ebooks',
  fte_feedback: 'https://storeapi.kobo.com/v1/products/ftefeedback',
  googledrive_link_account_start:
    'https://authorize.kobo.com/{region}/{language}/linkcloudstorage/provider/google_drive',
  image_host: '//cdn.kobo.com/book-images/',
  image_url_quality_template:
    'https://cdn.kobo.com/book-images/{ImageId}/{Width}/{Height}/{Quality}/{IsGreyscale}/image.jpg',
  image_url_template: 'https://cdn.kobo.com/book-images/{ImageId}/{Width}/{Height}/false/image.jpg',
  instapaper_enabled: 'True',
  instapaper_env_url: 'https://www.instapaper.com/api/kobo',
  instapaper_link_account_start: 'https://authorize.kobo.com/{region}/{language}/linkinstapaper',
  kda_store_browser_redirect_url: '',
  kobo_audiobooks_credit_redemption: 'True',
  kobo_audiobooks_enabled: 'True',
  kobo_dropbox_link_account_enabled: 'True',
  kobo_googledrive_link_account_enabled: 'True',
  kobo_nativeborrow_enabled: 'True',
  kobo_privacyCentre_url: 'https://www.kobo.com/privacy',
  kobo_redeem_enabled: 'True',
  kobo_subscriptions_enabled: 'True',
  kobo_superpoints_enabled: 'True',
  kobo_wishlist_enabled: 'True',
  library_items: 'https://storeapi.kobo.com/v1/user/library',
  library_metadata: 'https://storeapi.kobo.com/v1/library/{Ids}/metadata',
  library_stack: 'https://storeapi.kobo.com/v1/user/stacks/{LibraryItemId}',
  library_sync: 'https://storeapi.kobo.com/v1/library/sync',
  love_points_redemption_page:
    'https://www.kobo.com/{region}/{language}/KoboSuperPointsRedemption?productId={ProductId}',
  oauth_host: 'https://oauth.kobo.com',
  password_retrieval_page: 'https://www.kobo.com/passwordretrieval.html',
  privacy_page: 'https://www.kobo.com/privacypolicy?style=onestore',
  product_recommendations: 'https://storeapi.kobo.com/v1/products/{ProductId}/recommendations',
  product_reviews: 'https://storeapi.kobo.com/v1/products/{ProductIds}/reviews',
  purchase_buy_templated: 'https://www.kobo.com/{region}/{language}/checkoutoption/{ProductId}',
  reading_services_host: 'https://readingservices.kobo.com',
  reading_state: 'https://storeapi.kobo.com/v1/library/{Ids}/state',
  registration_page: 'https://authorize.kobo.com/signup?returnUrl=https://kobo.com/',
  review: 'https://storeapi.kobo.com/v1/products/reviews/{ReviewId}',
  review_sentiment:
    'https://storeapi.kobo.com/v1/products/reviews/{ReviewId}/sentiment/{Sentiment}',
  sign_in_page: 'https://auth.kobobooks.com/ActivateOnWeb',
  social_host: 'https://social.kobobooks.com',
  store_home: 'www.kobo.com/{region}/{language}',
  store_host: 'www.kobo.com',
  store_search: 'https://www.kobo.com/{region}/{language}/Search?Query={query}',
  subs_landing_page: 'https://www.kobo.com/{region}/{language}/plus',
  subs_management_page: 'https://www.kobo.com/{region}/{language}/account/subscriptions',
  subs_plans_page: 'https://www.kobo.com/{region}/{language}/plus/plans',
  subs_purchase_buy_templated:
    'https://www.kobo.com/{region}/{language}/Checkoutoption/{ProductId}/{TierId}',
  subscription_publisher_price_page: '',
  taste_profile: 'https://storeapi.kobo.com/v1/products/tasteprofile',
  tags: 'https://storeapi.kobo.com/v1/library/tags',
  user_platform: 'https://storeapi.kobo.com/v1/user/platform',
  user_profile: 'https://storeapi.kobo.com/v1/user/profile',
  user_ratings: 'https://storeapi.kobo.com/v1/user/ratings',
  user_recommendations: 'https://storeapi.kobo.com/v1/user/recommendations',
  user_reviews: 'https://storeapi.kobo.com/v1/user/reviews',
  user_wishlist: 'https://storeapi.kobo.com/v1/user/wishlist',
  userguide_host: 'https://ereaderfiles.kobo.com',
  wishlist_page: 'https://www.kobo.com/{region}/{language}/account/wishlist',
})
